//! `winnt.sif` answer-file generator for XP unattended installs.
//!
//! XP setup checks for `winnt.sif` (or `I386\winnt.sif`) at boot. If found,
//! it reads the file and pre-answers prompts: EULA, partition choice,
//! product key, user/computer name, time zone, etc. Without it the user has
//! to click through every prompt — fine for one-off installs, annoying for
//! repeatable workflows.
//!
//! The format is the same INI-flavour as txtsetup.sif; CRLF line endings.

/// User-supplied values for the answer file. Any `None` falls back to a
/// sensible default — except `product_key`, which we leave empty so setup
/// still prompts (and the user isn't tempted to commit a key by accident).
#[derive(Debug, Default)]
pub struct UnattendedOptions {
    pub product_key: Option<String>,
    pub computer_name: Option<String>,
    pub full_name: Option<String>,
}

/// Generate a minimal `winnt.sif` that has just enough to drive the
/// WinSetupFromUSB rename-script hooks (`[SetupParams] UserExecute` at end
/// of text-mode, `[GuiRunOnce]` after GUI-mode) and the `MsDosInitiated`
/// flag that USB-boot installs require. No EULA skip, no product key, no
/// computer-name automation — the user clicks through GUI-mode prompts.
///
/// This is the file we write when `--xp-unattended` is NOT passed. Without
/// it, GUI-mode setup prompts for the Windows XP CD because there's no
/// `UserExecute` hook to run `ren_fold.cmd`, which means `$WIN_NT$.~LS`
/// stays named the canonical name and XP's boot-volume sanity checks abort.
pub fn generate_minimal() -> String {
    let lines: Vec<&str> = vec![
        ";",
        "; winnt.sif generated by usbwin (v0.3 XP, rename-hook only)",
        ";",
        "[Data]",
        "    MsDosInitiated=\"1\"",
        "    Floppyless=\"1\"",
        // [Unattended] must be present (even empty) to suppress XP's
        // F8/Recovery Console prompt at the start of GUI-mode setup —
        // per RMPrepUSB tutorial 102.
        "",
        "[Unattended]",
        "",
        "[SetupParams]",
        // Runs at the end of text-mode setup, before the GUI-mode reboot.
        // Renames \$WIN_NT$.~BT and \$WIN_NT$.~LS on the USB so GUI-mode
        // setup's boot-volume sanity checks don't choke.
        "    UserExecute = \"ren_fold.cmd\"",
        "",
        "[GuiRunOnce]",
        // Runs once after first login of the installed Windows. Renames
        // the folders back, leaving the USB stick reusable.
        "    \"undoren.cmd\"",
        "",
    ];
    let mut out = lines.join("\r\n");
    out.push_str("\r\n");
    out
}

/// Generate the contents of `winnt.sif`. Returns a CRLF-terminated string
/// ready to write to `I386/winnt.sif` on the USB.
pub fn generate(opts: &UnattendedOptions) -> String {
    let full_name = opts.full_name.as_deref().unwrap_or("usbwin user");
    let computer = opts.computer_name.as_deref().unwrap_or("*");

    let mut lines: Vec<String> = vec![
        ";".into(),
        "; winnt.sif generated by usbwin (v0.3 XP unattended)".into(),
        ";".into(),
        "[Data]".into(),
        "    AutoPartition=0".into(),
        // MsDosInitiated="1" tells setup it was bootstrapped from
        // MS-DOS / a custom loader (which a USB install effectively is —
        // we chainload setupldr.bin from boot.ini, not a CD). "0" makes
        // setup expect CD media and fail to find source files mid-install.
        // Per WinSetupFromUSB-style recipe (jaclaz / wimb).
        "    MsDosInitiated=\"1\"".into(),
        "    UnattendedInstall=Yes".into(),
        "    Floppyless=\"1\"".into(),
        "".into(),
        "[Unattended]".into(),
        "    UnattendMode=ReadOnly".into(),
        "    OemPreinstall=No".into(),
        "    OemSkipEula=Yes".into(),
        "    TargetPath=\\WINDOWS".into(),
        "    FileSystem=LeaveAlone".into(),
        "    WaitForReboot=No".into(),
        "".into(),
        "[SetupParams]".into(),
        // See generate_minimal() for context.
        "    UserExecute = \"ren_fold.cmd\"".into(),
        "".into(),
        "[GuiRunOnce]".into(),
        "    \"undoren.cmd\"".into(),
        "".into(),
        "[GuiUnattended]".into(),
        "    AdminPassword=*".into(),
        "    EncryptedAdminPassword=NO".into(),
        "    AutoLogon=No".into(),
        "    OEMSkipRegional=1".into(),
        "    TimeZone=4".into(),
        "    OemSkipWelcome=1".into(),
        "".into(),
        "[UserData]".into(),
    ];
    if let Some(k) = &opts.product_key {
        lines.push(format!("    ProductKey={k}"));
    }
    lines.push(format!("    FullName=\"{full_name}\""));
    lines.push("    OrgName=\"\"".into());
    lines.push(format!("    ComputerName={computer}"));
    lines.extend([
        "".into(),
        "[Identification]".into(),
        "    JoinWorkgroup=WORKGROUP".into(),
        "".into(),
        "[Networking]".into(),
        "    InstallDefaultComponents=Yes".into(),
        "".into(),
        "[Branding]".into(),
        "    BrandIEUsingUnattended=Yes".into(),
        "".into(),
        "[Proxy]".into(),
        "    Proxy_Enable=0".into(),
        "    Use_Same_Proxy=0".into(),
        "".into(),
        "[Display]".into(),
        "    BitsPerPel=32".into(),
        "    Xresolution=1024".into(),
        "    YResolution=768".into(),
        "".into(),
    ]);
    let mut out = lines.join("\r\n");
    out.push_str("\r\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_generation_smoke() {
        let s = generate(&UnattendedOptions::default());
        assert!(s.contains("[Unattended]"));
        assert!(s.contains("FullName=\"usbwin user\""));
        assert!(s.contains("ComputerName=*"));
        assert!(!s.contains("ProductKey="));
    }

    #[test]
    fn with_product_key() {
        let s = generate(&UnattendedOptions {
            product_key: Some("XXXXX-XXXXX-XXXXX-XXXXX-XXXXX".to_string()),
            ..Default::default()
        });
        assert!(s.contains("ProductKey=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"));
    }

    #[test]
    fn with_custom_names() {
        let s = generate(&UnattendedOptions {
            full_name: Some("Alice".to_string()),
            computer_name: Some("VINTAGE-XP".to_string()),
            ..Default::default()
        });
        assert!(s.contains("FullName=\"Alice\""));
        assert!(s.contains("ComputerName=VINTAGE-XP"));
    }

    #[test]
    fn full_includes_rename_hooks() {
        let s = generate(&UnattendedOptions::default());
        assert!(s.contains("[SetupParams]"));
        assert!(s.contains("UserExecute = \"ren_fold.cmd\""));
        assert!(s.contains("[GuiRunOnce]"));
        assert!(s.contains("\"undoren.cmd\""));
    }

    #[test]
    fn minimal_has_rename_hooks_and_no_unattended_payload() {
        let s = generate_minimal();
        assert!(s.contains("[Data]"));
        assert!(s.contains("MsDosInitiated=\"1\""));
        // Empty [Unattended] section is required to suppress F8 prompt.
        assert!(s.contains("[Unattended]"));
        assert!(s.contains("[SetupParams]"));
        assert!(s.contains("UserExecute = \"ren_fold.cmd\""));
        assert!(s.contains("[GuiRunOnce]"));
        assert!(s.contains("\"undoren.cmd\""));
        // Should NOT contain the full-unattended product-key / GUI bits.
        assert!(!s.contains("UnattendedInstall=Yes"));
        assert!(!s.contains("[UserData]"));
        assert!(!s.contains("OemSkipEula"));
    }

    #[test]
    fn crlf_line_endings() {
        let s = generate(&UnattendedOptions::default());
        assert!(s.contains("\r\n"));
        // No bare LF (other than what's inside CRLF).
        let crlf = s.matches("\r\n").count();
        let total_lf = s.matches('\n').count();
        assert_eq!(crlf, total_lf);
    }
}
