//! `winnt.sif` answer-file generator for XP unattended installs.
//!
//! XP setup checks for `winnt.sif` (or `I386\winnt.sif`) at boot. If found,
//! it reads the file and pre-answers prompts: EULA, partition choice,
//! product key, user/computer name, time zone, etc. Without it the user has
//! to click through every prompt — fine for one-off installs, annoying for
//! repeatable workflows.
//!
//! The format is the same INI-flavour as txtsetup.sif; CRLF line endings.

/// User-supplied values for the answer file. Any `None` falls back to a
/// sensible default — except `product_key`, which we leave empty so setup
/// still prompts (and the user isn't tempted to commit a key by accident).
#[derive(Debug, Default)]
pub struct UnattendedOptions {
    pub product_key: Option<String>,
    pub computer_name: Option<String>,
    pub full_name: Option<String>,
}

/// Generate the contents of `winnt.sif`. Returns a CRLF-terminated string
/// ready to write to `I386/winnt.sif` on the USB.
pub fn generate(opts: &UnattendedOptions) -> String {
    let full_name = opts.full_name.as_deref().unwrap_or("usbwin user");
    let computer = opts.computer_name.as_deref().unwrap_or("*");

    let mut lines: Vec<String> = vec![
        ";".into(),
        "; winnt.sif generated by usbwin (v0.3 XP unattended)".into(),
        ";".into(),
        "[Data]".into(),
        "    AutoPartition=0".into(),
        "    MsDosInitiated=\"0\"".into(),
        "    UnattendedInstall=Yes".into(),
        "".into(),
        "[Unattended]".into(),
        "    UnattendMode=ReadOnly".into(),
        "    OemPreinstall=No".into(),
        "    OemSkipEula=Yes".into(),
        "    TargetPath=\\WINDOWS".into(),
        "    FileSystem=LeaveAlone".into(),
        "    WaitForReboot=No".into(),
        "".into(),
        "[GuiUnattended]".into(),
        "    AdminPassword=*".into(),
        "    EncryptedAdminPassword=NO".into(),
        "    AutoLogon=No".into(),
        "    OEMSkipRegional=1".into(),
        "    TimeZone=4".into(),
        "    OemSkipWelcome=1".into(),
        "".into(),
        "[UserData]".into(),
    ];
    if let Some(k) = &opts.product_key {
        lines.push(format!("    ProductKey={k}"));
    }
    lines.push(format!("    FullName=\"{full_name}\""));
    lines.push("    OrgName=\"\"".into());
    lines.push(format!("    ComputerName={computer}"));
    lines.extend([
        "".into(),
        "[Identification]".into(),
        "    JoinWorkgroup=WORKGROUP".into(),
        "".into(),
        "[Networking]".into(),
        "    InstallDefaultComponents=Yes".into(),
        "".into(),
        "[Branding]".into(),
        "    BrandIEUsingUnattended=Yes".into(),
        "".into(),
        "[Proxy]".into(),
        "    Proxy_Enable=0".into(),
        "    Use_Same_Proxy=0".into(),
        "".into(),
        "[Display]".into(),
        "    BitsPerPel=32".into(),
        "    Xresolution=1024".into(),
        "    YResolution=768".into(),
        "".into(),
    ]);
    let mut out = lines.join("\r\n");
    out.push_str("\r\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_generation_smoke() {
        let s = generate(&UnattendedOptions::default());
        assert!(s.contains("[Unattended]"));
        assert!(s.contains("FullName=\"usbwin user\""));
        assert!(s.contains("ComputerName=*"));
        assert!(!s.contains("ProductKey="));
    }

    #[test]
    fn with_product_key() {
        let s = generate(&UnattendedOptions {
            product_key: Some("XXXXX-XXXXX-XXXXX-XXXXX-XXXXX".to_string()),
            ..Default::default()
        });
        assert!(s.contains("ProductKey=XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"));
    }

    #[test]
    fn with_custom_names() {
        let s = generate(&UnattendedOptions {
            full_name: Some("Alice".to_string()),
            computer_name: Some("VINTAGE-XP".to_string()),
            ..Default::default()
        });
        assert!(s.contains("FullName=\"Alice\""));
        assert!(s.contains("ComputerName=VINTAGE-XP"));
    }

    #[test]
    fn crlf_line_endings() {
        let s = generate(&UnattendedOptions::default());
        assert!(s.contains("\r\n"));
        // No bare LF (other than what's inside CRLF).
        let crlf = s.matches("\r\n").count();
        let total_lf = s.matches('\n').count();
        assert_eq!(crlf, total_lf);
    }
}
